{% set name = "anchor-annotator" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/A/Anchor_annotator/Anchor_annotator-{{ version }}.tar.gz
  sha256: a83abb3497cc9fee818711066940b711e70edb19a1c61f6e87fd63f57dcce827

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.9
    - montreal-forced-aligner
    - pyside6
    - pyqtgraph
    - resampy
    - librosa
    - numpy
    - pysoundfile
    - sqlalchemy
    - scikit-learn
    - biopython
    - dataclassy
    - kalpy
    - pynini
    - pyyaml
    - tqdm
    - psycopg2

test:
  imports:
    - anchor
  requires:
    - pip
    - kaldi =*=cpu*
  commands:
    - mfa anchor --help

about:
  home: https://github.com/MontrealCorpusTools/Anchor-annotator
  summary: Anchor annotator is a program for inspecting corpora for the Montreal Forced Aligner and correcting transcriptions and pronunciations
  description: |
    Anchor annotator is a program for inspecting corpora for the Montreal Forced Aligner and 
    correcting transcriptions and pronunciations.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://anchor-annotator.readthedocs.io/en/latest/
  dev_url: https://github.com/MontrealCorpusTools/Anchor-annotator

extra:
  recipe-maintainers:
    - mmcauliffe
