{% set name = "anchor-annotator" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/A/Anchor_annotator/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 41278bb3d34cf39942009938b01686e6fdf8eb1367ae8dc901bd89a9cf5ab09b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.9
    - montreal-forced-aligner >3.0
    - qt6-main
    - qt6-multimedia
    - pyside6
    - pyqtgraph
    - librosa
    - numpy
    - pysoundfile
    - sqlalchemy
    - scikit-learn
    - biopython
    - dataclassy
    - kalpy =*=cpu*
    - pynini
    - pyyaml
    - tqdm
    - psycopg2
  run_constrained:
    - montreal-forced-aligner
    - pyside6

test:
  requires:
    - pip
  imports:
    - anchor.command_line
  commands:
    - mfa anchor --help

about:
  home: https://github.com/MontrealCorpusTools/Anchor-annotator
  summary: Anchor annotator is a program for inspecting corpora for the Montreal Forced Aligner and correcting transcriptions and pronunciations
  description: |
    Anchor annotator is a program for inspecting corpora for the Montreal Forced Aligner and 
    correcting transcriptions and pronunciations.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://anchor-annotator.readthedocs.io/en/latest/
  dev_url: https://github.com/MontrealCorpusTools/Anchor-annotator

extra:
  recipe-maintainers:
    - mmcauliffe
