{% set name = "anchor-annotator" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/A/Anchor_annotator/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a4447379149cee85540d7a6b29f8268cc16050f426e16a6d6ad2e29fc8ed2ccd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - montreal-forced-aligner >3.0
    - qt6-main
    - qt6-multimedia
    - pyside6
    - pyqtgraph
    - librosa
    - numpy
    - pysoundfile
    - sqlalchemy
    - scikit-learn
    - biopython
    - dataclassy
    - kalpy
    - pynini
    - pyyaml
    - tqdm
    - psycopg2
  run_constrained:
    - pyside6

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - anchor.command_line
  commands:
    - mfa anchor --help

about:
  home: https://github.com/MontrealCorpusTools/Anchor-annotator
  summary: Anchor annotator is a program for inspecting corpora for the Montreal Forced Aligner and correcting transcriptions and pronunciations
  description: |
    Anchor annotator is a program for inspecting corpora for the Montreal Forced Aligner and 
    correcting transcriptions and pronunciations.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://anchor-annotator.readthedocs.io/en/latest/
  dev_url: https://github.com/MontrealCorpusTools/Anchor-annotator

extra:
  recipe-maintainers:
    - mmcauliffe
