{% set name = "anchor-annotator" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/A/Anchor_annotator/Anchor_annotator-{{ version }}.tar.gz
  sha256: d9673dcb4d74a1cbab5932c7191194e310db13f25a0b61f7e9ee4cb519ede8f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python >=3.6
    - montreal-forced-aligner
    - pyside6
    - pyqtgraph

test:
  imports:
    - anchor
  requires:
    - pip
  commands:
    - mfa anchor --help

about:
  home: https://github.com/MontrealCorpusTools/Anchor-annotator
  summary: 'Anchor annotator is a program for inspecting corpora for the Montreal Forced Aligner and correcting transcriptions and pronunciations'
  description: |
    Anchor annotator is a program for inspecting corpora for the Montreal Forced Aligner and 
    correcting transcriptions and pronunciations.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://anchor-annotator.readthedocs.io/en/latest/
  dev_url: https://github.com/MontrealCorpusTools/Anchor-annotator

extra:
  recipe-maintainers:
    - mmcauliffe
